#!/usr/bin/env bash
# Installs, configures, and starts the server

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
